MangaWeb/Models/AddMangaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MangaWeb.Models
{
    // ViewModel pour la page qui ajoute à la fois des mangas et des auteurs
    public class AddMangaViewModel
    {
        // Utilisé pour le formulaire d'ajout de manga
        public MangaFormModel Manga { get; set; }

        // Utilisé pour le formulaire d'ajout d'auteur
        public AuthorFormModel NewAuthor { get; set; }

        // Liste des auteurs pour le menu déroulant
        public IEnumerable<AuthorViewModel> Authors { get; set; }
    }

    // Modèle de formulaire pour un manga
    public class MangaFormModel
    {
        [Required]
        [StringLength(255)]
        public string Title { get; set; }

        public string Synopsis { get; set; }

        [DataType(DataType.Date)]
        public DateTime? PublicationDate { get; set; }

        [DataType(DataType.ImageUrl)]
        public string ImageUrl { get; set; }

        [Display(Name = "Author")]
        public int? AuthorId { get; set; }
    }

    // Modèle de formulaire pour un auteur
    public class AuthorFormModel
    {
        [Required]
        [StringLength(255)]
        public string Name { get; set; }

        public string Biography { get; set; }
    }

    // ViewModel pour un auteur
    public class AuthorViewModel
    {
        public int AuthorId { get; set; }
        public string Name { get; set; }
    }
}

MangaWeb/Models/AuthorViewModel.cs
using System.ComponentModel.DataAnnotations;

public class AuthorViewModel
{
    [Required]
    [StringLength(255)]
    public string Name { get; set; }

    public string Biography { get; set; }

    // Ajoutez d'autres propriétés au besoin, par exemple :
    // public IFormFile Photo { get; set; } pour un téléchargement d'image
}

MangaWeb/Models/ErrorViewModel.cs
namespace MangaWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MangaWeb/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MangaWeb.Models
{
    public class LoginViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

MangaWeb/Models/User.cs
namespace MangaWeb.Models
{
    public class User
    {
        // Ajoutez les propriétés selon votre API
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        // Vous pouvez ajouter d'autres propriétés nécessaires pour l'inscription
        public DateTime SignupDate { get; set; }
    }
}

MangaWeb/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using MangaWeb.Models;
using MangaWeb.Services;
using System.Threading.Tasks;

namespace MangaWeb.Controllers
{
    public class AccountController : Controller
    {
        private readonly UserService _userService;

        public AccountController(UserService userService)
        {
            _userService = userService;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                // Remplacer par la logique d'appel à l'API pour la vérification des identifiants
                var success = await _userService.ValidateUserAsync(model.Email, model.Password);
                if (success)
                {
                    // Logique de traitement après une connexion réussie
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Email ou mot de passe incorrect.");
                }
            }
            return View(model);
        }
    }
}

MangaWeb/Controllers/HomeController.cs
using MangaWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MangaWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MangaWeb/Controllers/MangaController.cs
using Microsoft.AspNetCore.Mvc;
using MangaWeb.Models;
using MangaWeb.Services;
using System.Threading.Tasks;

namespace MangaWeb.Controllers
{
    public class MangaController : Controller
    {
        private readonly MangaService _mangaService;

        public MangaController(MangaService mangaService)
        {
            _mangaService = mangaService;
        }

        // GET: Affiche la vue pour ajouter un Manga et un Auteur
        public async Task<IActionResult> AddMangaAndAuthor()
        {
            var authors = await _mangaService.GetAuthorsAsync();
            var viewModel = new AddMangaViewModel
            {
                Authors = authors, // Peuplez la liste des auteurs pour le menu déroulant
                Manga = new MangaFormModel(), // Initialisez Manga pour éviter les erreurs de référence nulle
                NewAuthor = new AuthorFormModel() // Initialisez NewAuthor pour le formulaire d'ajout d'auteur
            };

            return View(viewModel);
        }

        // POST: Ajoute un Manga à l'API
        [HttpPost]
        public async Task<IActionResult> AddManga(AddMangaViewModel viewModel)
        {
            if (ModelState.IsValid && viewModel.Manga != null)
            {
                var success = await _mangaService.AddMangaAsync(viewModel.Manga);
                if (success)
                {
                    return RedirectToAction("Index"); // Redirigez vers l'index ou une autre page appropriée
                }
            }

            // En cas d'échec, rechargez la liste des auteurs et affichez à nouveau le formulaire
            viewModel.Authors = await _mangaService.GetAuthorsAsync();
            return View("AddMangaAndAuthor", viewModel);
        }

        // POST: Ajoute un Auteur à l'API
        [HttpPost]
        public async Task<IActionResult> AddAuthor(AddMangaViewModel viewModel)
        {
            if (ModelState.IsValid && viewModel.NewAuthor != null)
            {
                var success = await _mangaService.AddAuthorAsync(viewModel.NewAuthor);
                if (success)
                {
                    // Si l'ajout de l'auteur réussit, redirigez pour ajouter un manga pour cet auteur
                    return RedirectToAction("AddMangaAndAuthor");
                }
            }

            // En cas d'échec, rechargez la liste des auteurs et affichez à nouveau le formulaire
            viewModel.Authors = await _mangaService.GetAuthorsAsync();
            return View("AddMangaAndAuthor", viewModel);
        }
    }
}

MangaWeb/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using MangaWeb.Services;
using MangaWeb.Models;

namespace MangaWeb.Controllers
{
    public class UserController : Controller
    {
        private readonly UserService _userService;

        public UserController(UserService userService)
        {
            _userService = userService;
        }

        // Afficher le formulaire
        public IActionResult Create()
        {
            return View();
        }

        // Traiter le formulaire
        [HttpPost]
        public async Task<IActionResult> Create(User user)
        {
            if (ModelState.IsValid)
            {
                await _userService.CreateUserAsync(user);
                return RedirectToAction("Index", "Home"); // Redirigez selon vos besoins
            }
            return View(user);
        }
    }
}

MangaWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Accueil MangaWorld";
}

<style>
    body {
        background: url('/images/giphy.gif') no-repeat center center fixed;
        background-size: cover;
        height: 100vh;
        overflow: hidden;
        color: #fff;
    }

    .welcome-container {
        text-align: center;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }

    .btn-manga {
        margin: 20px;
        background-color: #ff9800;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        text-decoration: none;
        font-size: 18px;
    }

    .btn-manga:hover {
        background-color: #e68900;
    }
</style>

<div class="welcome-container">
    <h1>Bienvenue sur MangaWorld</h1>
    <p>Découvrez un univers riche en mangas et anime!</p>
    <a href="/Account/Login" class="btn-manga">Se connecter</a>
    <a href="/User/Create" class="btn-manga">S'inscrire</a>
</div>

MangaWeb/Views/Manga/AddMangaAndAuthor.cshtml
@model MangaWeb.Models.AddMangaViewModel

@{
    ViewData["Title"] = "Ajouter Manga et Auteur";
}

<h2>Ajouter un Manga</h2>

<form asp-action="AddManga" asp-controller="Manga" method="post">
    <div class="form-group">
        <label asp-for="Manga.Title">Titre</label>
        <input asp-for="Manga.Title" class="form-control" />
        <span asp-validation-for="Manga.Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Manga.Synopsis">Synopsis</label>
        <textarea asp-for="Manga.Synopsis" class="form-control"></textarea>
        <span asp-validation-for="Manga.Synopsis" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Manga.PublicationDate">Date de publication</label>
        <input asp-for="Manga.PublicationDate" class="form-control" type="date" />
        <span asp-validation-for="Manga.PublicationDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Manga.ImageUrl">URL de l'image</label>
        <input asp-for="Manga.ImageUrl" class="form-control" />
        <span asp-validation-for="Manga.ImageUrl" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Manga.AuthorId">Auteur</label>
        <select asp-for="Manga.AuthorId" asp-items="@(new SelectList(Model.Authors, "AuthorId", "Name"))" class="form-control">
            <option value="">Choisir un auteur</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Ajouter Manga</button>
</form>

<button id="showAuthorForm" class="btn btn-secondary">Ajouter un nouvel auteur</button>

<div id="authorForm" style="display: none;">
    <h2>Ajouter un Auteur</h2>
    <form asp-action="AddAuthor" asp-controller="Manga" method="post">
        <div class="form-group">
            <label asp-for="NewAuthor.Name">Nom</label>
            <input asp-for="NewAuthor.Name" class="form-control" />
            <span asp-validation-for="NewAuthor.Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="NewAuthor.Biography">Biographie</label>
            <textarea asp-for="NewAuthor.Biography" class="form-control"></textarea>
            <span asp-validation-for="NewAuthor.Biography" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Ajouter Auteur</button>
    </form>
</div>

@section Scripts {
    <script>
        document.getElementById("showAuthorForm").addEventListener("click", function () {
            document.getElementById("authorForm").style.display = 'block';
            this.style.display = 'none';
        });
    </script>
}

MangaWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MangaWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MangaWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MangaWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div class="container">
            &copy; 2024 - MangaWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MangaWeb/Views/User/Create.cshtml
@model MangaWeb.Models.User

@{
    ViewData["Title"] = "Créer un utilisateur";
}

<h2>Créer un utilisateur</h2>

<form asp-controller="User" asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="Username">Username</label>
        <input asp-for="Username" class="form-control" />
        <span asp-validation-for="Username" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email">Email</label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Password">Password</label>
        <input asp-for="Password" class="form-control" type="password" />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Créer</button>
</form>